version: "3.9"

services:
  next:
    build:
      context: next
    restart: on-failure
    networks:
      - app-network
    volumes:
      - ./next:/var/src/next
      - /var/src/next/node_modules
      - /var/src/next/.next
    ports:
      - 3001:3001
    depends_on:
      - strapi

  strapi:
    image: strapi/strapi:3.3.4-node14-alpine
    restart: on-failure
    env_file: ./strapi/.env
    networks:
      - app-network
      - core-network
    volumes:
      - ./strapi:/var/src/strapi
    ports:
      - 1337:1337
    depends_on:
      - strapidb

  strapidb:
    image: mongo:4.4.2
    restart: on-failure
    env_file: ./.env.strapidb
    networks:
      - core-network
    volumes:
      - strapidb-volume:/data/db

  updater:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7-alpine3.8-2020-06-06
    environment:
      PORT: 1338
    restart: on-failure
    networks:
      - core-network
    volumes:
      - ./updater:/var/src/updater
    ports:
      - 1338:1338
    depends_on:
      - strapi
      - strapidb
      - grafanadb

  grafana:
    image: grafana/grafana:7.3.5
    restart: on-failure
    networks:
      - monitoring-network
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - grafanadb

  grafanadb:
    image: influxdb:1.8.3
    restart: on-failure
    env_file: ./.env.grafanadb
    networks:
      - monitoring-network
      - core-network
    volumes:
      - grafanadb-volume:/var/lib/influxdb

networks:
  app-network:
  core-network:
  monitoring-network:

volumes:
  strapidb-volume:
  grafana-volume:
  grafanadb-volume:
